### ISSUE TITLE
Code Quality: Update Stylelint to Match Code Guidelines

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8-ui/fabric8-ux#922]
Update the Stylelint configuration for fabric8-ui to match the [HTML/CSS Code Guidelines](https://fabric8-ui.github.io/fabric8-ux/code-guidelines).

**Comment by mindreeper2420** [comment]
Updated the following:
- Required that color variables be either hex codes or PatternFly variables.
   - allowed: `#fff` or `@color-pf-white`
   - not allowed: `white`
- Multiple Declarations require more than one line (cannot have a long string of declarations).
   **not allowed**
   ```css
      .block-1 { font-size: 1.2em; color: @color-pf-white; }
   ```
   **allowed**
   ```css
      .block-1 {
          font-size: 1.2em;
          color: @color-pf-white;
      }
   ```
- Require spaces between blocks for increased readability.
   ```css
      .block-1 {
          font-size: 1.2em;
      }

      .block-2 {
          font-weight: 700;
      }
   ```
- Comments must have white spaces between the `/*` and any text for increased readability.
   ```css
      /*
      ** This is a proper comment
       */
   ```
- Add the `fr` unit to the unit whitelist for future grid use.
- Updated the error message for when a leading zero is added to a property.
